AWSTemplateFormatVersion: '2010-09-09'
Description: AWS Serverless Application for IoT Door Unlocking

Resources:
  UnlockDoorFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs14.x
      Events:
        Api:
          Type: Api
          Properties:
            Path: /unlock
            Method: post

  DoorUnlockTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: DoorUnlockData
      AttributeDefinitions:
        - AttributeName: deviceId
          AttributeType: S
      KeySchema:
        - AttributeName: deviceId
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
